# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/docker/machine";
    fetch = {
      type = "git";
      url = "https://github.com/docker/machine";
      rev = "796b36730911f008d6c3e9d30a81330dd54ae091";
      sha256 = "065bam9s5yi89ddbx198p1gkdlpd2kzxs9lc1br5h16v6x1ig7kb";
    };
  }
  {
    goPackagePath = "github.com/libvirt/libvirt-go";
    fetch = {
      type = "git";
      url = "https://github.com/libvirt/libvirt-go";
      rev = "4a36356705fc68ccbe3e8724e0087cceefcdf3f0";
      sha256 = "0d05l9sz6pbdf943r4m5fik4cjfl8ls78341angr4f3gnl40k6y4";
    };
  }
]
